package: on 
javascripts:
  flash_socket:
    - public/javascripts/vendor/FABridge.js
    - public/javascripts/vendor/swfobject.js
    - public/javascripts/vendor/web_socket.js
  main:
    - public/javascripts/rails.js
    - public/javascripts/vendor/jquery.tipsy.js
    - public/javascripts/vendor/jquery.html5-placeholder-shim.js
    - public/javascripts/vendor/jqModal.js
    - public/javascripts/vendor/swfupload/swfupload.js
    - public/javascripts/vendor/jquery-ui-1.8.6.custom.min.js
    - public/javascripts/application.js    
    - public/javascripts/theme_browser.js
    - public/javascripts/wowo.js
  mobile:
    - public/javascripts/vendor/jquery144.min.js
    - public/javascripts/custom-mobile-scripting.js
    - public/javascripts/vendor/jquery-ui-1.8.6.custom.min.js
    - public/javascripts/vendor/jquery_mobile_a2.min.js
    - public/javascripts/mobile.js
  mailchimp:
    - public/javascripts/vendor/mailchimp/jquery.form.js
    - public/javascripts/vendor/mailchimp/jquery.validate.js
    - public/javascripts/vendor/mailchimp/jquery126.min.js
  aspects:
    - public/javascripts/vendor/jquery-ui-1.8.6.custom.min.js
    - public/javascripts/aspect-edit.js
    - public/javascripts/contact-list.js
  people:
    - public/javascripts/contact-list.js
  photos:
    - public/javascripts/photo-show.js

stylesheets:
  default:
    - public/stylesheets/application.css
    - public/stylesheets/ui.css
    - public/stylesheets/vendor/jquery.fancybox-1.3.1.css
    - public/stylesheets/vendor/fileuploader.css
    - public/stylesheets/vendor/tipsy.css
